name: flutter_map_weather
description: A starting point for Dart libraries or applications.
publish_to: none
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter_map: ^0.9.0
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.0
